import type { Shipment } from "./qc";
import { QCStatus } from "./qc";

export const DUMMY_SHIPMENTS: Shipment[] = [
  {
    id: "SHP001",
    supplier: "Acme Corp",
    items: ["Widget A", "Widget B"],
    expectedDate: "2024-07-20",
    status: QCStatus.Pending,
    level1Complete: false,
    level2Complete: false,
  },
  {
    id: "SHP002",
    supplier: "Beta Supplies",
    items: ["Gadget X"],
    expectedDate: "2024-07-18",
    status: QCStatus.Level1Complete,
    level1Complete: true,
    level2Complete: false,
  },
  {
    id: "SHP003",
    supplier: "Gamma Goods",
    items: ["Part Z", "Part Y", "Part X"],
    expectedDate: "2024-07-15",
    status: QCStatus.Completed,
    level1Complete: true,
    level2Complete: true,
    level1Data: {
      receivedDate: "2024-07-15",
      receivedBy: "John Doe",
      overallCondition: "Good",
      packagingIntegrity: "Intact",
      quantityReceived: 100,
      damages: "None",
      documentation: "Complete",
    },
    level2Data: {
      sampleSize: 10,
      itemsChecked: 10,
      totalItems: 100,
      passedItems: 10,
      failedItems: 0,
      defectTypes: [],
    },
  },
  {
    id: "SHP004",
    supplier: "Delta Distributors",
    items: ["Component Q"],
    expectedDate: "2024-07-22",
    status: QCStatus.Level2Complete,
    level1Complete: true,
    level2Complete: true,
    level1Data: {
      receivedDate: "2024-07-22",
      receivedBy: "Jane Smith",
      overallCondition: "Damaged",
      packagingIntegrity: "Torn",
      quantityReceived: 50,
      damages: "Box torn, 2 items broken",
      documentation: "Incomplete",
      notes: "Reported to supplier",
    },
    level2Data: {
      sampleSize: 5,
      itemsChecked: 5,
      totalItems: 50,
      passedItems: 3,
      failedItems: 2,
      defectTypes: ["Broken", "Scratched"],
      qualityNotes: "High defect rate",
    },
  },
];
